### PR TITLE
ceph-erasure-code-corpus: adding objects encoded using clay plugin

### PR DESCRIPTION
**Pull request by mynaramana**
ceph-erasure-code-corpus: adding objects encoded using clay code plugin

Signed-off-by: Myna <mynaramana@gmail.com>

### CODE REVIEW

**Comment by mynaramana** [comment]
@tchaikov , @liewegas let me know your comments!!

**Comment by liewegas** [comment]
1. Can you move the new tests into a new version directory, whatever `git describe` tells you?
2. You added ~350MB of new data.  Prior versions have <100mb each.  That's probably fine, just wanted to raise it in case anyone has concerns?

**Comment by tchaikov** [comment]
@mynaramana probably, we don't need to test *all* combinations of `stripe-width`, `scalar_mds`, `technique`, `k`, `m`, and `d`. in this change, you added all valid combination of following settings:

stripe-width: 4096,4651,1000,65000,65536
scalar_mds: isa, jerasure, shec
technique: cauchy,reed_sol_van,cauchy_good,cauchy_orig,liber8tion,reed_sol_r6_op,multiple,single
k,m,d:{2,2,3},{3,2,4},{4,2,5},{4,3,5},{4,3,6},{7,3,8},{7,3,9},{7,4,8},{7,4,9},{7,4,10},{8,3,9},{8,3,10},{8,4,9},{8,4,10},{8,4,11},{9,3,10},{9,3,11},{9,4,10},{9,4,11},

i think it's not necessary. because both isa and jerasure plugins are Vandermonde matrix-based Reed-Solomon coding. the former takes depends on ISA-l library from Intel, while the latter uses platform specific SIMD instruction sets like SSE2,SSE3 or neon extensions on ARM. so from some perspective, they are equivalent. the same appliy to multiple SHEC and (single) SHEC, the difference between single and multiple is but the internals of SHEC erasure codes. i think, probably we can pick one of them as a sample. as we already have good coverage of all erasure codec corpus.

so, i'd suggest instead of enumerating all combinations of settings, we can just pick a single representative scalar codec. along with different stripe-width, and k,m,d combinations.

also, please fold these two commits into a single one.

what do you think?

**Comment by mynaramana** [comment]
hi Kefu, Sage:

I have updated the changes you suggested. 

Thanks,
Myna.

**Comment by tchaikov** [comment]
@mynaramana no.  not all of my comments are addressed.
```
$ ls -ld v11.1.0/plugin\=clay\ stripe-width\=* | wc -l
     678
$ ls -ld v0.92-988/plugin\=clay\ stripe-width\=* | wc -l
    1112
$ ls -ld v11.1.0/plugin\=clay\ stripe-width\=*| grep shec | wc -l
     198
$ ls -ld v11.1.0/plugin\=clay\ stripe-width\=*| grep jerasure | wc -l
     360
$ ls -l v0.92-988/ |grep jerasure|grep cauchy_good|wc -l
     180
```
could you remove the clay erasure corpus in v0.92-988 and v11.1.0. the clay code was introduced by eb4070e458f753449497339182993a4294a8c5f1 , and per
```
$ git describe eb4070e458f753449497339182993a4294a8c5f1
v14.0.0-3924-geb4070e458
```
the corpus of clay codes should go to the directory of `v14.0.0-3924` .

and again, i'd suggest just pick one representative scalar erasure codec for building the corpus of clay code.

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
probably we should wait until https://github.com/ceph/ceph/pull/24586 gets merged so the test passes.

**Pull request merged**
