### PR TITLE
v0.92-988/non-regression.sh: use uname -m vs. uname -p or arch

### PR DESCRIPTION
**Pull request by dx9**

### CODE REVIEW

**Comment by dx9** [comment]
@tchaikov If https://github.com/ceph/ceph/pull/12294 is OK, can this get merged too?

**Comment by dx9** [comment]
@wjwithagen Are you ok with this?

**Comment by tchaikov** [comment]
@dx9 i am good with this, @wjwithagen what do you think?

**Review by tchaikov — APPROVED** [review]

**Comment by wjwithagen** [comment]
@tchaikov 
Sorry this is rather late, Still finding all kinds of buttons in GitHub.

But this would work oke under FreeBSD

**Pull request merged**
